name: bing_wallpaper_app
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
    sdk: ">=3.0.5 <4.0.0"

dependencies:
    flutter:
        sdk: flutter

    # Cupertino Icons font for iOS style icons.
    cupertino_icons: ^1.0.2

    # For dynamic color theming.
    dynamic_color: ^1.6.6

    # For accessing the file system.
    path_provider: ^2.1.3

    # For styled toast messages.
    flutter_styled_toast: ^2.1.3

    # For setting wallpaper on Linux.
    wallman:
        git:
            url: https://github.com/imhemish/wallman.git
            ref: master

    # For setting wallpaper on Android.
    flutter_wallpaper_manager: ^0.0.4

    # For making HTTP requests.
    http: ^1.2.1

    # For parsing HTML.
    html: ^0.15.4

    # For internationalization.
    intl: 0.19.0

    # For caching network images.
    cached_network_image: ^3.3.1

    # For downloading files in the background.
    # (* Addition config is required for various platforms)
    background_downloader: ^8.5.2

    # For handling permissions.
    # (* Addition config is required for various platforms)
    permission_handler: ^11.3.1

    # For creating card swiper.
    flutter_card_swiper: ^7.0.1

    # For parsing command line arguments.
    args: ^2.5.0

dev_dependencies:
    flutter_test:
        sdk: flutter

    # For encouraging good coding practices.
    flutter_lints: ^2.0.0

flutter:
    uses-material-design: true

    assets:
        - assets/icons/
        - assets/images/

dependency_overrides:
    ffi: any
    http: any